### ISSUE TITLE
Informacion de funcion

### ISSUE THREAD

**Issue by Jmaria1149** [andrethomas/TasmotaSlave#1]
good afternoon, could you tell me what function I use and how to execute a command in trasmota from arduino, thank you very much.

**Comment by andrethomas** [comment]
Currently, only 2 commands are implemented on the Tasmota side.

`SlaveReset` will reset the arduino using the configured reset pin

`SlaveSend xxxx` will send `xxx` to the `attach_FUNC_COMMAND_SEND` callback on the Arduino UNO/Mini side

If you look at the SlaveSendCommand example for the UNO/Mini side you can test the builtin LED by using commands `SlaveSend ON` and `SlaveSend OFF` commands from the Tasmota side.

You should note that the user_FUNC_RECEIVE function on the UNO/Mini side will receive the data sent by the `SlaveSend` command from Tasmota so it is case sensitive for the given example.

**Comment by Jmaria1149** [comment]
Thanks for your quick response. Surely I have not explained well because of the translator. What I intend is to send commands to the trasmota from the arduino and that he executes them. It would also be very useful to send text from Arduino to Tasmot similar to the "SerialReceive" command, thank you very much for your attention.

**Comment by andrethomas** [comment]
Right, I understood you the wrong way around.

What you're asking for is not yet implemented but I will see how to implement it over the weekend when I get a moment.

**Comment by Jmaria1149** [comment]
Good morning, I will wait for that implementation.
Thank you,

**Comment by andrethomas** [comment]
You can try the updated copy of this library - The xdrv_31_tasmota_slave.ino in the Tasmota repository was also updated so you will need to get a fresh copy of the repo from there.

It adds a new command ExecuteCommand(char *cmnd) which allows you to send commands back to the Tasmota device.

**Comment by andrethomas** [comment]
PR to Tasmota was merged so you can use the development codebase from there.
