### ISSUE TITLE
New exemple Event raised by the slave

### ISSUE THREAD

**Issue by aymeric106** [andrethomas/TasmotaSlave#2]
Hello, thank you for this project.
Could you write an exemple .INO that implement this type of event:

An input GPIO connected to the arduino changes it state -> a MQTT telemetry is sent.

Most of the example are triggered by the Tasmota master, not the slave.

Thanks a lot

**Comment by arovak** [comment]
Hello, what you want can be done with the `slave.ExecuteCommand`
Take a look at the BlinkSendCommand.ino example.

You can use that command anywhere in you code to send a command to tasmota to publish what you need over mqtt.

**Comment by aymeric106** [comment]
so I can add the slave.ExecuteCommand in the main loop() ?

**Comment by andrethomas** [comment]
@aymeric106 yes, you can execute any command that you would usually execute from the Tasmota console... the `publish` command is no exception :)
