### ISSUE TITLE
Read value from Tasmota

### ISSUE THREAD

**Issue by j0seph1387** [andrethomas/TasmotaSlave#5]
Hello, can you create an example of how I can receive values? I want to send values from Tasmota to TasmotaSlave and then use them as PWM values for a pin.
Example:

Tasmota:
SlaveSend Fan1 192

TasmotaSlave:
void user_FUNC_RECEIVE (char * data)
{
   if (! strcmp (data, "Fan1")) ...
     analogWrite (Fan1, 192);
   }

**Comment by arovak** [comment]
I use this in my project.

``` 
char sCmd[20],sVal[20],sDat[3];
memset(sCmd, 0 ,sizeof(sCmd));
memset(sVal, 0 ,sizeof(sVal));
memset(sDat, 0 ,sizeof(sDat));
sscanf(data,"%s %s %s",sCmd,sVal,sDat);

if (!strcmp(sCmd, "POST")) {
   uint8_t logType = atoi(sVal);
}
```
